language: go

go:
  - "1.11"

go_import_path: github.com/kubeflow/mxnet-operator

install:
  # get coveralls.io support
  - go get github.com/mattn/goveralls
  # Install golangci-lint
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.7

script:
  - hack/verify-codegen.sh
  - go build -o mxnet-operator.v1beta1 github.com/kubeflow/mxnet-operator/cmd/mxnet-operator.v1beta1
  - go build -o mxnet-operator.v1 github.com/kubeflow/mxnet-operator/cmd/mxnet-operator.v1
  - golangci-lint run --config=linter_config.yaml ./...
  # We customize the build step because by default
  # Travis runs go test -v ./... which will include the vendor
  # directory.
  # With go 1.9 vendor will be automatically excluded.
  # For now though we just run all tests in pkg.
  # And we can not use ** because goveralls uses filepath.Match
  # to match ignore files and it does not support it.
  - goveralls -service=travis-ci -v -package ./pkg/... -ignore "pkg/client/*/*.go,pkg/client/*/*/*.go,pkg/client/*/*/*/*.go,pkg/client/*/*/*/*/*.go,pkg/client/*/*/*/*/*/*.go,pkg/client/*/*/*/*/*/*/*.go,pkg/apis/mxnet/*/zz_generated.*.go"

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
