apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd-v1beta1.yaml
- service-account.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- deployment.yaml

images:
- name: mxjob/mxnet-operator
  newTag: v1beta1
